from __future__ import annotations

import json
import shutil
from pathlib import Path

from streamcraft.core.pipeline import generate_run_id


def migrate_legacy_dataset_root(dataset_root: Path) -> None:
    if not dataset_root.exists():
        print(f"[migrate] dataset root not found: {dataset_root}")
        return

    for streamer_dir in sorted(p for p in dataset_root.iterdir() if p.is_dir()):
        runs_dir = streamer_dir / "runs"
        runs_dir.mkdir(parents=True, exist_ok=True)

        legacy_has_artifacts = any(
            [
                (streamer_dir / "clips").exists(),
                (streamer_dir / "manifest.csv").exists(),
                (streamer_dir / "manifest.jsonl").exists(),
                any(streamer_dir.glob("*_segments.json")),
                (streamer_dir / "segments.json").exists(),
            ]
        )
        if not legacy_has_artifacts:
            continue

        run_id = generate_run_id()
        run_dir = runs_dir / run_id
        run_dir.mkdir(parents=True, exist_ok=True)

        moved_any = False
        move_candidates = [
            streamer_dir / "clips",
            streamer_dir / "manifest.csv",
            streamer_dir / "manifest.jsonl",
            streamer_dir / "segments.json",
            streamer_dir / "dataset_segments.json",
        ]
        move_candidates.extend(streamer_dir.glob("*_segments.json"))
        move_candidates.extend(streamer_dir.glob("*_segment_review.json"))

        for src in move_candidates:
            if not src.exists():
                continue
            dst = run_dir / src.name
            if dst.exists():
                continue
            shutil.move(str(src), str(dst))
            moved_any = True

        if not moved_any:
            shutil.rmtree(run_dir, ignore_errors=True)
            continue

        metadata_path = run_dir / "run_metadata.json"
        if not metadata_path.exists():
            metadata = {
                "run_id": run_id,
                "created_at": None,
                "vod_url": None,
                "streamer": streamer_dir.name,
                "vod_identifier": None,
                "status": "legacy_migrated",
                "params": {},
                "stats": {},
                "artifacts": {
                    "migration": {
                        "source": "legacy_flat",
                        "note": "Generated by migrate_legacy_runs.py",
                    }
                },
            }
            metadata_path.write_text(json.dumps(metadata, indent=2, ensure_ascii=False), encoding="utf-8")

        print(f"[migrate] {streamer_dir.name}: legacy artifacts moved to runs/{run_id}")


if __name__ == "__main__":
    migrate_legacy_dataset_root(Path("dataset"))
